const routes = {
    start: '/',
    managerhome: '/managerhome',
    managerprofile: '/managerhome/managerprofile',
    managecustomer: '/managerhome/managecustomer',
    managestaff: '/managerhome/managestaff',
    managervehicleS: '/managervehicle/modelS',
    managereport: '/managerhome/managereport',
    managerchat: '/managerhome/managerchat',
    managecar: '/managerhome/managecar',
    manageshop: '/managerhome/manageshop',
    customerhome: '/customerhome',
    customerprofile: '/customerhome/profile',
    customerpayment: '/customerhome/payment',
    customerorderhis: '/customerhome/orderhis',
    customerreport: '/customerhome/report',
    shoppingcart: '/customerhome/shoppingcart',
    shop: '/shop',
    shopaccessories: '/shop/accessories',
    shopmerchandise: '/shop/merchandise',
    vehicle: '/vehicle',
    login: '/login',
    register: '/register',
    forgotpassword: 'login/forgotpassword',
    staffhome: '/staffhome',
    staffreport: '/staffhome/report',
    stafforder: '/staffhome/order',
    staffcustomer: '/staffhome/customer',
    staffcar: '/staffhome/car',
    staffshop: '/staffhome/shop',
    staffprofile: '/staffhome/profile',
    vehicledetail: '/vehicledetail/:id',
    productdetail: '/shop/:id',
    bookappointment: '/customerhome/bookappointment',
    coupon: '/customerhome/coupon',
    staffcoupon: '/staffhome/coupon'
};
    


export default routes;
